jobs:
  build:
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        java-version: 11
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Env
      run: env
    - continue-on-error: true
      if: ${{ (github.event_name == 'pull_request' && github.base_ref == 'GROOVY_3_0_X')
        || github.ref == 'refs/heads/GROOVY_3_0_X' }}
      name: Checkout Grails 4.1.x (master)
      run: cd .. && git clone --depth 1 https://github.com/grails/grails-core.git
        -b master
    - continue-on-error: true
      if: ${{ (github.event_name == 'pull_request' && github.base_ref == 'GROOVY_2_5_X')
        || github.ref == 'refs/heads/GROOVY_2_5_X' }}
      name: Checkout Grails 4.0.x (4.0.x)
      run: cd .. && git clone --depth 1 https://github.com/grails/grails-core.git
        -b 4.0.x
    - continue-on-error: true
      name: Build and install groovy (no docs)
      run: ./gradlew clean install -x groovydoc -x javadoc -x javadocAll -x groovydocAll
        -x asciidoc -x docGDK --no-build-cache --no-scan --no-daemon
      timeout-minutes: 60
    - continue-on-error: true
      name: Set CI_GROOVY_VERSION for Grails
      run: echo "CI_GROOVY_VERSION=$(cat gradle.properties | grep groovyVersion |
        cut -d\= -f2 |  tr -d '[:space:]')" >> $GITHUB_ENV
    - continue-on-error: true
      name: echo CI_GROOVY_VERSION
      run: echo $CI_GROOVY_VERSION
    - continue-on-error: true
      name: Build Grails
      run: cd ../grails-core && ./gradlew clean build test -x groovydoc --no-build-cache
        --no-scan --no-daemon
      timeout-minutes: 60
    strategy:
      fail-fast: true
      matrix:
        os:
        - ubuntu-latest
name: Grails Joint Validation Build
on:
  repository_dispatch:
    types: trigger-ga___grails-joint-validation.yml
permissions:
  contents: read
