env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
jobs:
  additional:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        check-latest: true
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Test with Gradle
      run: ./gradlew test
      timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        java:
        - 12
        - 13
        - 14
        - 15
        - 16
        - 18
        - 19
        - 20
        - 22
        os:
        - ubuntu-latest
  ea:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Download JDK ${{ matrix.jdk }}
      run: wget -c ${{ matrix.jdk }} -O /tmp/openjdk.tar.gz
    - continue-on-error: true
      name: Set up JDK ${{ matrix.jdk }}
      run: mkdir -p /home/runner/openjdk && tar -xvf /tmp/openjdk.tar.gz -C /home/runner/openjdk
        && chmod -R 755 /home/runner/openjdk && mv /home/runner/openjdk/jdk*/* /home/runner/openjdk/
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        check-latest: true
        distribution: zulu
        java-version: 21
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Test with Gradle
      run: ./gradlew test -Ptarget.java.home=/home/runner/openjdk
      timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        jdk:
        - https://download.java.net/java/early_access/jdk23/25/GPL/openjdk-23-ea+25_linux-x64_bin.tar.gz
        os:
        - ubuntu-latest
  lts:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        check-latest: true
        distribution: zulu
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Test with Gradle
      run: ./gradlew test
      timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        java:
        - 11
        - 17
        - 21
        os:
        - ubuntu-latest
name: Build and test
on:
  repository_dispatch:
    types: trigger-ga___groovy-build-test.yml
permissions:
  contents: read
