jobs:
  test:
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        check-latest: true
        distribution: zulu
        java-version: 21
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Test with Gradle
      run: ./gradlew -Pcoverage=true jacocoAllReport
      timeout-minutes: 60
    - continue-on-error: true
      name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
name: Build and test for coverage
on:
  repository_dispatch:
    types: trigger-ga___groovy-build-coverage.yml
permissions:
  contents: read
