jobs:
  test:
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        check-latest: true
        distribution: zulu
        java-version: 21
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: Check licenses with rat
      run: ./gradlew rat
      timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
name: Check licenses
on:
  repository_dispatch:
    types: trigger-ga___groovy-rat-check.yml
permissions:
  contents: read
