jobs:
  dist:
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Install graphviz
      run: sudo apt-get install -y graphviz
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        check-latest: true
        distribution: zulu
        java-version: 21
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Build and package
      run: ./gradlew clean dist --no-build-cache --no-scan --refresh-dependencies
      timeout-minutes: 90
    - continue-on-error: true
      name: Publish to Local Repository
      run: ./gradlew publishMavenPublicationToLocalFileRepository --no-build-cache
        --no-scan --refresh-dependencies
      timeout-minutes: 90
    - continue-on-error: true
      name: Move binary distribution
      run: mkdir -p build/distributions/binary/ && mv subprojects/groovy-binary/build/distributions/apache-groovy-binary-*.zip
        build/distributions/binary/
    - continue-on-error: true
      name: Move src distribution
      run: mkdir -p build/distributions/src/ && mv subprojects/groovy-binary/build/distributions/apache-groovy-src-*.zip
        build/distributions/src/
    - continue-on-error: true
      name: Move docs distribution
      run: mkdir -p build/distributions/docs/ && mv subprojects/groovy-binary/build/distributions/apache-groovy-docs-*.zip
        build/distributions/docs/
    - continue-on-error: true
      name: Move sdk distribution
      run: mkdir -p build/distributions/sdk/ && mv subprojects/groovy-binary/build/distributions/apache-groovy-sdk-*.zip
        build/distributions/sdk/
    - continue-on-error: true
      name: Upload binary distribution
      uses: actions/upload-artifact@v4
      with:
        name: apache-groovy-binary-SNAPSHOT
        path: build/distributions/binary/
    - continue-on-error: true
      name: Upload src distribution
      uses: actions/upload-artifact@v4
      with:
        name: apache-groovy-src-SNAPSHOT
        path: build/distributions/src/
    - continue-on-error: true
      name: Upload docs distribution
      uses: actions/upload-artifact@v4
      with:
        name: apache-groovy-docs-SNAPSHOT
        path: build/distributions/docs/
    - continue-on-error: true
      name: Upload sdk distribution
      uses: actions/upload-artifact@v4
      with:
        name: apache-groovy-sdk-SNAPSHOT
        path: build/distributions/sdk/
    strategy:
      fail-fast: true
      matrix:
        os:
        - ubuntu-latest
name: Distribute SNAPSHOT
on:
  repository_dispatch:
    types: trigger-ga___groovy-build-dist.yml
permissions:
  contents: read
