jobs:
  build:
    env:
      DEVELOCITY_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-java@v4
      with:
        check-latest: true
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      name: env
      run: env
    - continue-on-error: true
      name: Create init script to enable mavenLocal()
      run: cd .. && echo "allprojects { repositories { mavenLocal() } }" > maven-local-init.gradle
    - continue-on-error: true
      name: Checkout Micronaut Core
      run: cd .. && git clone --depth 1 https://github.com/micronaut-projects/micronaut-core
        -b 4.4.x
    - continue-on-error: true
      name: Checkout Micronaut Groovy
      run: cd .. && git clone --depth 1 https://github.com/micronaut-projects/micronaut-groovy
        -b 4.3.x
    - continue-on-error: true
      name: Build and install groovy (no docs)
      run: ./gradlew --no-build-cache --no-daemon --no-scan clean install -x asciidoc
        -x docGDK -x groovydoc -x javadoc -x javadocAll -x groovydocAll
      timeout-minutes: 60
    - continue-on-error: true
      name: Set CI_GROOVY_VERSION
      run: echo "CI_GROOVY_VERSION=$(cat gradle.properties | grep groovyVersion |
        cut -d\= -f2 |  tr -d '[:space:]')" >> $GITHUB_ENV
    - continue-on-error: true
      name: echo CI_GROOVY_VERSION
      run: echo $CI_GROOVY_VERSION
    - continue-on-error: true
      name: Test Micronaut Core
      run: cd ../micronaut-core && ./gradlew --init-script ../maven-local-init.gradle
        --no-build-cache --no-daemon --no-scan clean test -x :test-suite-kotlin-ksp:test
        -x :discovery-core:test -x :test-suite-netty-ssl-graalvm:test -x :test-suite-kotlin:test
        -x :inject-kotlin:test -x :inject-kotlin-test:test -PgroovyVersion=$CI_GROOVY_VERSION
      timeout-minutes: 60
    - continue-on-error: true
      name: Check Micronaut Groovy
      run: cd ../micronaut-groovy && ./gradlew --init-script ../maven-local-init.gradle
        --no-build-cache --no-daemon --no-scan clean check -PgroovyVersion=$CI_GROOVY_VERSION
      timeout-minutes: 60
    strategy:
      fail-fast: true
name: Micronaut Joint Validation Build
on:
  repository_dispatch:
    types: trigger-ga___micronaut-joint-validation.yml
permissions:
  contents: read
